try to fix error not showing in examples

diff --git a/examples/check-examples b/examples/check-examples
--- a/examples/check-examples
+++ b/examples/check-examples
@@ -28,5 +28,21 @@ do
     mv python/${name}-original.py python/${file}
 
     # Run script
-    ./answer_input_prompts ${file} $PYTKET_REMOTE_QUANTINUUM_USERNAME $PYTKET_REMOTE_QUANTINUUM_PASSWORD
+    ./answer_input_prompts ${file} $PYTKET_REMOTE_QUANTINUUM_USERNAME $PYTKET_REMOTE_QUANTINUUM_PASSWORD >out.txt 2>err.txt
+    echo "output of run:"
+    cat out.txt
+    echo "error output of run:"
+    cat err.txt
+    ERRS=$(cat err.txt)
+    if [ -n "$ERRS" ]
+    then
+        echo "example check failed"
+        exit 1
+    fi
+
+    if grep -Fq "Error" "out.txt"
+    then
+        exit 1
+    fi
+
 done
